services:
  - type: web
    name: media-code-bot
    runtime: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 8024370472:AAFBMFl0XbcNXrnDW6TqMZTBZ9Lj3tN7ofI